No pbs
fit52/results pull request #19
Opened 2019-01-27 18:54 UTC by BenVardy

Add a flag to the load command to add an event without it being processed for PBs, global records, or calculating age grades. Also modifies the rebuild script to respect the noPb property in the event.

2019-01-28 09:10 UTC, markvardy requested changes
Very minor change, otherwise good

2019-01-28 09:10 UTC, markvardy commented on src/event-input/processEvent.js
> +    if (Object.keys(argv)   .length === 0) throw new Error('No files specified');
Delete extraneous whitespace please

2019-01-28 09:30 UTC, ajdaniel commented on src/event-input/processEvent.js
> +            for (let i = 0; i < results.length; i++) {
FYI This can be made more readable with `.forEach` ie:

```js
results.forEach(result => {
	globalRecords = checkRecords(globalRecords, result, result.gender);
}
```

2019-01-28 09:30 UTC, ajdaniel submitted a review, later dismissed
Looks good to me

2019-02-13 15:33 UTC, markvardy approved these changes

2019-02-13 15:36 UTC, merged