Fix pbs not correctly displaying
fit52/results pull request #24
Opened 2019-03-31 07:32 UTC by BenVardy

Rebuilding the data base now also updates results as well as runners

2019-04-01 10:52 UTC, markvardy commented
@BenVardy what testing have you done? We could test on a copy of the database and verify by running the UI locally against that copy.

Of course ideally we need actual automated tests. I've opened an issue for this.

2019-04-01 12:22 UTC, ajdaniel requested changes
I agree with @markvardy can we run some tests here

2019-04-01 12:22 UTC, ajdaniel commented on src/event-input/calcPb.js
> +    if (!fastest /* Therefore also !slowest */) {
This comment confuses me. I think you should place it on the next line. I'm guessing you're saying:
```
// There isn't a fastest time, thus there is no slowest time, so set them both
```

2019-04-01 12:22 UTC, ajdaniel commented on src/event-input/calcPb.js
> +        runner.stats[`records${distance}k`].slowest = result;
We should start moving towards "functional" programming whereby we do not alter any of the parameters in the function. Altering the parameters changes the variables outside of the function's scope and can have unintended side-effects. I know that you pass back the changed runner at the end of this function, but it's a good practice to adopt whereby you do not modify the parameter, just pass back a new version of the runner. You can do this either by cloning the data at the top of the function, or when you pass it back, pass back a merge of the old and the new e.g.:

```js
return {
	runner: {
		...runnerFromParameter,
		stats: newStats
	}
};
```

2019-04-01 12:22 UTC, ajdaniel commented on src/event-input/calcPb.js
> +    if (!bestAgeGrade /* Therefore also !worstAgeGrade */) {
Same as the previous comment about your comment, perhaps you could explain a bit better here. It almost seems like you're saying if(!bestAgeGrade) === if (!worstAgeGrade) which may also be true, but let's remove ambiguity

2019-05-07 17:42 UTC, ajdaniel approved these changes
Looks good to me!

2019-05-07 17:43 UTC, ajdaniel commented
@BenVardy I've approved your changes. Sorry it took me so long. I was gonna merge it but I just wanna check you're happy to do that, in case you were planning on doing tests.

2019-05-08 06:32 UTC, markvardy commented
Ben & discussed it, manual testing has been done already.

2019-05-08 06:32 UTC, merged