Changes as per request in #5
fit52/results pull request #7
Opened 2018-10-30 07:49 UTC by BenVardy

Change 'event/stats' to 'event/counts'
Store age grade as percent to 2d.p

2018-10-30 16:14 UTC, ajdaniel requested changes
Just a minor change request please.

2018-10-30 16:14 UTC, ajdaniel commented on design/database.d.ts
>          no2k: number
As part of my request, could you also rename the properties of `count` to something a bit more readable, and do not include `no`? such as `2k` `5k` `runners` `volunteers`? The "number" part of the name is implied by being in the "count" property.

2018-10-31 13:17 UTC, markvardy commented
@BenVardy Does the change from `stats` to `count` mean repopulating the database? If so, how can this be done for the existing data?

2018-10-31 13:39 UTC, ajdaniel commented
@markvardy yes great point. We need all records to still match the same document design else the ui would fail when processing all documents for rendering

2018-11-02 14:23 UTC, markvardy approved these changes
I'm happy with this. We'll need to run the update script as soon as we've merged the changes, of course.

I assume you've tested the util script to update the db? (we need to talk about automated tests 😄 )

@ajdaniel you happy?

2018-11-02 16:29 UTC, ajdaniel approved these changes
I approve these changes. You could have saved some legwork by using the [ES6 object spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) operator like so:

```js
    docs = res.docs.map(doc => {
        if (doc.counts) {
            console.log(`'${doc._id}' already using 'count'`);
            return doc;
        }
        const { stats, ...restOfDoc } = doc;
        return {
            ...restOfDoc, // put the rest of the doc back without knowing the structure
            counts: {
                twok: stats.no2k,
                fivek: stats.no5k,
                total: stats.nototal,
                firstTimers: stats.noFirstTimes,
                pbs: stats.noPbs,
                volunteers: stats.noVolunteers
            },
        };
    });
```

2018-11-05 20:27 UTC, merged